const fs = require('fs');
let text = fs.readFileSync('d:/seogentest/src/pages/ArticleEditor.tsx', 'utf8');

const regex = /markdown = markdown\.replace[\s\S]*?;\s*const parsedHtml/m;

const replacement = `markdown = markdown.replace(/สุญญากาศ/g, 'สูญญากาศ').replace(/สูญากาศ/g, 'สูญญากาศ').replace(/สุญากาศ/g, 'สูญญากาศ').replace(/มือาชีพ/g, 'มืออาชีพ').replace(/อาหาร้อน/g, 'อาหารร้อน').replace(/กรไกร/g, 'กรรไกร').replace(/จาการปนเปื้อน/g, 'จากการปนเปื้อน').replace(/จาการซีล/g, 'จากการซีล').replace(/ต้องการะดับ/g, 'ต้องการระดับ').replace(/ข้อควระวัง/g, 'ข้อควรระวัง').replace(/ช่วยับยั้ง/g, 'ช่วยยับยั้ง').replace(/การู้วิธี/g, 'การรู้วิธี').replace(/ช่วยืนยัน/g, 'ช่วยยืนยัน').replace(/พบ่อย/g, 'พบบ่อย').replace(/ช่วยืด/g, 'ช่วยยืด').replace(/โครงสร้างเซล์/g, 'โครงสร้างเซลล์').replace(/ก่อนำ/g, 'ก่อนนำ').replace(/ใน้ำเดือด/g, 'ในน้ำเดือด').replace(/สนิทั้ง/g, 'สนิททั้ง').replace(/การั่วไหล/g, 'การรั่วไหล').replace(/รอย่น/g, 'รอยย่น').replace(/เนื้อาหาร/g, 'เนื้ออาหาร').replace(/เห็ดิบ/g, 'เห็ดดิบ').replace(/หรือาจ/g, 'หรืออาจ').replace(/อย่าง่าย/g, 'อย่างง่าย').replace(/รอยซีลเดิมาซีล/g, 'รอยซีลเดิมมาซีล').replace(/หนึ่งมื้น/g, 'หนึ่งมื้อ').replace(/ออกจากัน/g, 'ออกจากกัน').replace(/กระดูก่อน/g, 'กระดูกก่อน').replace(/ความชื้นี้/g, 'ความชื้นนี้').replace(/ระบไร้อากาศ/g, 'ระบบไร้อากาศ').replace(/การักษา/g, 'การรักษา').replace(/หรือุ่น/g, 'หรืออุ่น').replace(/แบ Sous-vide/g, 'แบบ Sous-vide').replace(/ถูกักไว้/g, 'ถูกกักไว้').replace(/หรืออกซิเจน/g, 'หรือออกซิเจน').replace(/เนื่องจาก๊าซ/g, 'เนื่องจากก๊าซ').replace(/สามารถูกดึง/g, 'สามารถถูกดึง').replace(/แบเรียบ/g, 'แบบเรียบ').replace(/ขั้นตอนี้/g, 'ขั้นตอนนี้').replace(/ตรวจับ/g, 'ตรวจจับ').replace(/ผลัพธ์/g, 'ผลลัพธ์').replace(/หัวดูดึง/g, 'หัวดูด').replace(/ฟุ้ติดลงไป/g, 'รัดติดลงไป').replace(/ดูดสุญากาศ/g, 'ดูดสูญญากาศ').replace(/ธุรกิจำเป็น/g, 'ธุรกิจจำเป็น').replace(/ก้อน้ำแข็ง/g, 'ก้อนน้ำแข็ง').replace(/ฟ่างอากาศ/g, 'ฟองอากาศ').replace(/หรือุณหภูมิ/g, 'หรืออุณหภูมิ').replace(/อุณหูมิห้อง/g, 'อุณหภูมิห้อง').replace(/ปากามาร์คเกอร์/g, 'ปากกามาร์คเกอร์').replace(/แน่นิ่ง/g, 'แนบสนิท').replace(/เปรอฝาแฝด/g, 'เปรอะเปื้อน').replace(/แบไม่มี/g, 'แบบไม่มี').replace(/เช่น้ำซุป/g, 'เช่นน้ำซุป').replace(/เซล์/g, 'เซลล์').replace(/ระบบบบบ/g, 'ระบบ').replace(/ควบคุมมมม/g, 'ควบคุม').replace(/ป้องกัน้ำ/g, 'ป้องกันน้ำ').replace(/ประอุณหภูมิ/g, 'ปรับอุณหภูมิ').replace(/บอบาง/g, 'บอบบาง').replace(/ผักาดหอม/g, 'ผักกาดหอม').replace(/เอื้อำนวย/g, 'เอื้ออำนวย').replace(/แบเต็มที่/g, 'แบบเต็มที่').replace(/เครื่องแบ /g, 'เครื่องแบบ ').replace(/แบ Nozzle/g, 'แบบ Nozzle').replace(/แบ External/g, 'แบบ External').replace(/แบ Chamber/g, 'แบบ Chamber').replace(/ระบ Pulse/g, 'ระบบ Pulse').replace(/ทิชู่/g, 'ทิชชู่').replace(/อาจะเท/g, 'อาจจะเท').replace(/กึ่งแข็งแข็ง/g, 'กึ่งแข็ง').replace(/เติบโตได้อาหาร/g, 'เติบโตได้ อาหาร').replace(/ไม่ได้การซีล/g, 'ไม่ได้ การซีล').replace(/ปลอดภัยิ่ง/g, 'ปลอดภัยยิ่ง').replace(/การับมือ/g, 'การรับมือ');\n  const parsedHtml`;

text = text.replace(regex, replacement);
fs.writeFileSync('d:/seogentest/src/pages/ArticleEditor.tsx', text, 'utf8');
console.log('Fixed ArticleEditor.tsx');
