import localforage from 'localforage';

async function compressBase64Image(dataUri: string, maxWidth = 900, quality = 0.70): Promise<string> {
  if (typeof window === 'undefined') return dataUri;
  return new Promise((resolve) => {
    if (!dataUri || !dataUri.startsWith('data:image/')) {
      resolve(dataUri);
      return;
    }
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.src = dataUri;
    img.onload = () => {
      try {
        const canvas = document.createElement('canvas');
        let width = img.width;
        let height = img.height;

        if (width > maxWidth) {
          height = Math.round((height * maxWidth) / width);
          width = maxWidth;
        }

        canvas.width = width;
        canvas.height = height;
        const ctx = canvas.getContext('2d');
        if (ctx) {
          ctx.fillStyle = '#ffffff';
          ctx.fillRect(0, 0, width, height);
          ctx.drawImage(img, 0, 0, width, height);
          const compressed = canvas.toDataURL('image/jpeg', quality);
          resolve(compressed);
        } else {
          resolve(dataUri);
        }
      } catch (err) {
        console.warn('Compression error during generation:', err);
        resolve(dataUri);
      }
    };
    img.onerror = () => {
      resolve(dataUri);
    };
  });
}

/**
 * ระบบแก้ไขคำผิดไทย (Post-processing) — 3 ชั้น
 * ทำงานหลัง AI สร้างบทความเสร็จแล้ว ไม่กินเวลาเพิ่มระหว่าง generate
 */
function fixThaiTypos(text: string): string {
  // ชั้นที่ 1 — Regex generic: วรรณยุกต์ซ้ำ, พยัญชนะซ้ำ, สระซ้ำ, ๆ ซ้ำ
  text = text.replace(/([่้๊๋ัีึื])\1+/g, '$1');           // วรรณยุกต์ซ้ำ เช่น ่่ ัั ็็
  text = text.replace(/([ก-ฮ])(\1){2,}/g, '$1$1');         // พยัญชนะซ้ำ 3+ ตัว → 2 ตัว (ชื่อย่อย)
  // NOTE: ลบ regex "พยัญชนะซ้ำ 2 ตัว → 1 ตัว" ออก เพราะทำลายคำไทยที่ถูกต้อง
  // เช่น แบบ(บบ) โรงงาน(งง) เกมมือถือ(มม) สมมุติ(มม) กรรม(รร) ชั้นนำ(นน) บันไดดัง(ดด)
  // ภาษาไทยมีคำที่มีพยัญชนะเดียวกันซ้ำ 2 ตัวติดกันโดยชอบธรรม ห้ามตัด
  text = text.replace(/(เกี่ยว)ว+/g, '$1');                // สระซ้ำ เช่น เกี่ยวว → เกี่ยว
  text = text.replace(/(ๆ){2,}/g, 'ๆ');                    // ๆ ซ้ำ
  text = text.replace(/([a-zA-Z])\1{2,}/g, '$1$1');        // อังกฤษซ้ำ 3+ → 2

  // ชั้นที่ 2 — Dictionary คำผิดเฉพาะ (~34 คู่)
  const dict: Array<[RegExp, string]> = [
    // คำทับศัพท์ผิด / สับสนความหมาย
    [/พื้นที่แคง/g, 'พื้นที่แคบ'],
    [/ปั้มจูนเบรก/g, 'ก้ามปูเบรก'],
    [/กลองเบรก/g, 'ดรัมเบรก'],
    [/ของไหมเบรก/g, 'น้ำมันเบรก'],
    [/สะเก็ดรังแก้ว/g, 'สะเก็ดรอยเชื่อม'],
    [/ฆาตกริ่ง/g, 'ฆาตกรเงียบ'],
    [/จานเบรคบุบเสีย/g, 'จานเบรกคด'],
    [/สอดแนมตามกฎหมาย/g, 'ปฏิบัติตามกฎหมาย'],
    [/กระจกเข็นน้ำฝน/g, 'กระจกไล่ฝ้า'],
    [/การประกันตัว(?!\s*(คน|นัก|ผู้))/g, 'การประกันภัย'],
    [/มูลฝอย/g, 'สิ่งสกปรก'],
    // คำสะกดผิดพบบ่อย
    [/ผู้ขับขี้/g, 'ผู้ขับขี่'],
    [/กระทันหัน/g, 'กะทันหัน'],
    [/พนังพิง/g, 'พนักพิง'],
    [/บิดเคี้ยว/g, 'บิดเบี้ยว'],
    [/กระทัดรัด/g, 'กะทัดรัด'],
    // คำแปลผิด / คำประดิษฐ์ขึ้น (hallucination)
    [/ไหครบสุด/g, 'หลังคาป้องกัน'],
    [/สวมงาม/g, 'สวยงาม'],
    [/ทะลักทะลาม/g, 'พังทลาย'],
    [/ยนต์กล/g, 'กลไก'],
    [/ถูกขบวนเคียน/g, 'ถูกล้อเลียน'],
    // ศัพท์เทคนิครถยก — แปลผิด
    [/ส้อมยก/g, 'งา'],
    [/(?<!รถ|ยาน|เครื่อง)ง่าม(?!อก)/g, 'งา'],
    [/เสากระโชง/g, 'เสายก'],
    [/เสากระโดง/g, 'เสายก'],
    [/มุมมองบอด/g, 'จุดบอด'],
    // วลีที่ AI มักเขียนผิด
    [/มุมมองโดยรอบดีกว่า/g, 'มีทัศนวิสัยที่ดี'],
    [/น้ำหมัก(?!\s*(ข้าว|หมัก))/g, 'คราบน้ำ'],
    [/ดีบุก(?!\s*(แร่|จีน|เหมือง))/g, 'สิ่งสกปรก'],
    [/ลมหนาวจัด/g, 'อันตรายร้ายแรง'],
    [/โครงสร้างไฮเดรลิค/g, 'ระบบไฮดรอลิก'],
  ];
  for (const [pattern, replacement] of dict) {
    text = text.replace(pattern, replacement);
  }

  // ชั้นที่ 3 — Inline quick-fix ทีละคำ (ตรวจรอบๆ พยัญชนะซ้ำที่ regex ชั้น 1 อาจพลาด)
  text = text.replace(/(?<=[ก-ฮ])\s+(?=[่้๊๋ัีึื])/g, '');  // เช่น "ก ่" → "ก่"
  text = text.replace(/(?<=[่้๊๋ัีื])\s+(?=[ก-ฮ])/g, '');  // เช่น "่ ก" → "่ก"

  return text;
}

/**
 * AI Proofreading — ส่งบทความกลับให้ AI ตรวจและแก้คำผิด/คำตก
 * รองรับทุกภาษา ใช้ model + API key เดียวกับที่ใช้ generate
 *
 * จุดประสงค์: แก้ปัญหาบาง model (เช่น DeepSeek V4 Flash) ที่มักตัดตัวอักษร
 * ตัวสุดท้ายของคำทิ้ง (เช่น "ออกแบ" → "ออกแบบ") ซึ่ง regex/dictionary จับไม่ได้ทุกกรณี
 *
 * Safety: หากเกิดข้อผิดพลาด หรือผลลัพธ์สั้นผิดปกติ หรือ image placeholder หาย
 * จะคืนค่า text เดิม (graceful fallback) เพื่อไม่ให้บทความเสียหาย
 */
async function proofreadWithAI(
  text: string,
  config: any,
  apiKey: string,
  requestModel: string
): Promise<string> {
  // ข้ามถ้าบทความสั้นเกินไป หรือไม่มี API key
  // (marker '__USE_GLOBAL__' ถือว่ามีค่า ส่วน model server จะ override เอง)
  if (!text || text.length < 50 || !apiKey || !apiKey.trim()) {
    return text;
  }

  const proofreadPrompt = `You are a meticulous proofreader. The text below was generated by an AI model and may contain subtle spelling errors — especially DROPPED or missing characters at the end of words (for example in Thai: "ออกแบ" missing the final "บ", or "หรือาคาร" missing the "อ"), as well as typos and missing spaces between words.

YOUR TASK: Fix ONLY spelling errors, missing characters, dropped letters, and missing spaces between merged words. Keep everything else EXACTLY the same.

STRICT RULES (MUST FOLLOW):
1. Do NOT rewrite, rephrase, reorganize, paraphrase, summarize, or expand the content.
2. Do NOT change the meaning, tone, style, or level of detail.
3. Do NOT modify any Markdown formatting — keep all headings (#, ##), bold (**), italic (*), tables (|), lists (-, 1.), and links intact.
4. Do NOT touch anything inside square brackets such as [GEMINI_IMAGE_PROMPT:...], URLs, code blocks, or HTML tags.
5. Keep the SAME language — do NOT translate.
6. Do NOT add any preface, explanation, notes, or commentary.
7. Output ONLY the corrected text, starting directly with the first word of the article.

Corrected text:`;

  try {
    const abortController = new AbortController();
    const timeout = setTimeout(() => abortController.abort(), 180000); // 3 นาที

    const response = await fetch('/api/gemini/generate', {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": apiKey
      },
      body: JSON.stringify({
        model: requestModel,
        contents: `${proofreadPrompt}\n\n${text}`,
        // ไม่ส่ง baseUrl เมื่อใช้ global — ให้ server ดึงจาก DB
        config: apiKey === '__USE_GLOBAL__' ? {} : { baseUrl: config.textApiBaseUrl }
      }),
      signal: abortController.signal
    });
    clearTimeout(timeout);

    if (!response.ok) {
      const errData = await response.json().catch(() => ({}));
      console.warn('[Proofread] API failed:', response.status, errData?.error || '', '— returning original text');
      return text;
    }

    const data = await response.json();
    const corrected: string = data.text || data.candidates?.[0]?.content?.parts?.[0]?.text || "";

    // Guard: ถ้าผลลัพธ์ว่าง หรือสั้นผิดปกติ (น้อยกว่าครึ่งหนึ่งของต้นฉบับ) ให้คืนค่าเดิม
    if (!corrected || corrected.trim().length < text.length * 0.5) {
      console.warn('[Proofread] Result too short or empty, returning original');
      return text;
    }

    // Guard: ตรวจสอบว่า image placeholders ยังอยู่ครบ (ไม่ให้ AI ลบรูปทิ้ง)
    const placeholderRegex = /\[GEMINI_IMAGE_PROMPT:[^\]]+\]/g;
    const originalImageCount = (text.match(placeholderRegex) || []).length;
    const correctedImageCount = (corrected.match(placeholderRegex) || []).length;
    if (originalImageCount !== correctedImageCount) {
      console.warn(`[Proofread] Image placeholder count mismatch (${originalImageCount} → ${correctedImageCount}), returning original`);
      return text;
    }

    // ลบ code block wrapper ถ้า AI หุ้มด้วย ```markdown ... ```
    const cleaned = corrected
      .replace(/^```(?:markdown|md)?\s*\n/i, '')
      .replace(/\n```\s*$/i, '')
      .trim();

    console.log('[Proofread] Successfully proofread article');
    return cleaned;
  } catch (err: any) {
    console.warn('[Proofread] Error, returning original:', err.message);
    return text;
  }
}

async function resolvePromptUrls(promptText: string): Promise<string> {
  if (!promptText) return promptText;
  const urlRegex = /(https?:\/\/[^\s<>'"]+)/g;
  const urls = promptText.match(urlRegex);
  if (!urls || urls.length === 0) return promptText;

  const uniqueUrls = Array.from(new Set(urls));
  // ดึงเนื้อหาจากทุก URL พร้อมกัน (parallel)
  const fetchResults = await Promise.all(
    uniqueUrls.map(async (url) => {
      try {
        const response = await fetch('/api/fetch-url', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ url })
        });
        if (response.ok) {
          const data = await response.json();
          if (data.text) {
            return `\n\n--- ข้อมูลจากเว็บ ${url} ---\n${data.text}\n--- จบข้อมูลจากเว็บ ---`;
          }
        }
      } catch (e) {
        console.warn("Could not fetch url content:", url, e);
      }
      return '';
    })
  );

  let resolvedText = promptText;
  for (const content of fetchResults) {
    if (content) resolvedText += content;
  }
  return resolvedText;
}

// Concurrency limiter สำหรับรูปภาพ — จำกัดไม่เหนือ 3 รูปพร้อมกัน เพื่อไม่ให้เกิน browser connection limit
const MAX_CONCURRENT_IMAGES = 5;
const imageQueue: Array<{ fn: () => Promise<string>; resolve: (v: string) => void; reject: (e: Error) => void }> = [];
let imageQueueRunning = 0;

function scheduleImage(fn: () => Promise<string>): Promise<string> {
  return new Promise((resolve, reject) => {
    imageQueue.push({ fn, resolve, reject });
    processImageQueue();
  });
}

function processImageQueue() {
  while (imageQueueRunning < MAX_CONCURRENT_IMAGES && imageQueue.length > 0) {
    imageQueueRunning++;
    const item = imageQueue.shift()!;
    item.fn()
      .then(item.resolve)
      .catch(item.reject)
      .finally(() => {
        imageQueueRunning--;
        processImageQueue();
      });
  }
}

// Helper: สร้างรูปภาพเดี่ยว
async function generateSingleImage(
  index: number,
  imagePrompt: string,
  ar: string,
  config: any,
  resolvedImageApiPrompt: string
): Promise<string> {
  // บังคับใช้ global image API Key (admin ตั้งค่า) เสมอ
  const imageGenApiKey = "__USE_GLOBAL__";

  // บังคับให้ prompt เป็นภาษาอังกฤษเท่านั้น + ห้ามมีข้อความ/ตัวอักษรในภาพ
  // เพราะ AI image gen (Seedream/DALL-E) มักเจนข้อความแปลกๆ ถ้า prompt เป็นภาษาอื่น
  const englishOnlyPrompt = imagePrompt
    .replace(/[\u0E00-\u0E7F]/g, ' ') // ลบตัวอักษรไทยออก
    .replace(/\s+/g, ' ')
    .trim();
  const safePrompt = englishOnlyPrompt || imagePrompt;

  const finalImagePrompt = resolvedImageApiPrompt
    ? `Style Instructions: ${resolvedImageApiPrompt}\nSubject: ${safePrompt}\nCRITICAL: No text, no words, no letters, no watermark in the image.`
    : `${safePrompt}\nCRITICAL: No text, no words, no letters, no watermark in the image.`;

  const imageRequestModel = '__GLOBAL_IMAGE__';

  // Retry สูงสุด 2 ครั้ง สำหรับ network errors
  let lastError: any = null;
  for (let attempt = 0; attempt < 3; attempt++) {
    try {
      const imgAbort = new AbortController();
      const imgTimeout = setTimeout(() => imgAbort.abort(), 60000); // 60 วินาที
      const imageRes = await fetch('/api/gemini/generate', {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": imageGenApiKey
        },
        body: JSON.stringify({
          model: imageRequestModel,
          contents: finalImagePrompt,
          // ไม่ส่ง baseUrl — ให้ server ดึงจาก DB
          config: { aspectRatio: ar }
        }),
        signal: imgAbort.signal
      });
      clearTimeout(imgTimeout);

      if (!imageRes.ok) {
        const errorData = await imageRes.json().catch(() => null);
        let errorMessage = errorData?.error || "Image generation failed";
        if (typeof errorMessage === 'string') {
          try {
            const parsed = JSON.parse(errorMessage);
            if (parsed.error && parsed.error.message) errorMessage = parsed.error.message;
          } catch (e) { }
        }
        throw new Error(typeof errorMessage === 'string' ? errorMessage : JSON.stringify(errorMessage));
      }

      const imgData = await imageRes.json();
      let base64 = "";
      let mimeType = "image/png";

      for (const part of imgData.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          base64 = part.inlineData.data;
          mimeType = part.inlineData.mimeType || "image/png";
          break;
        }
      }
      if (base64) {
        let dataUri = `data:${mimeType};base64,${base64}`;
        try {
          dataUri = await compressBase64Image(dataUri, 1440, 0.85);
        } catch (cErr) {
          console.warn("Compression failed", cErr);
        }
        const imageId = `gemini_img_${Date.now()}_${index}`;
        await localforage.setItem(imageId, dataUri);
        return imageId;
      }
      throw new Error("ระบบสร้างรูปภาพสำเร็จแต่ไม่พบข้อมูลภาพ");
    } catch (err: any) {
      lastError = err;
      // Retry สำหรับ network errors เท่านั้น (ไม่ retry สำหรับ 429, 403, quota)
      const msg = err?.message || '';
      if (msg.includes('429') || msg.includes('quota') || msg.includes('RESOURCE_EXHAUSTED') || msg.includes('403') || msg.includes('overdue') || msg.includes('Forbidden')) {
        throw err; // ไม่ retry quota/account errors
      }
      if (attempt < 2) {
        console.warn(`[Image ${index}] Attempt ${attempt + 1} failed: ${msg}, retrying in 2s...`);
        await new Promise(r => setTimeout(r, 2000));
      }
    }
  }
  throw lastError;
}

// Post-processing: กระจายรูปภาพให้สมดุล ถ้า AI กองรูปไว้ท้ายบทความ
// ตรวจจับ: ถ้ารูป 70%+ อยู่ในครึ่งหลังของบทความ → ย้ายไปแทรกหลัง H2 ต่างๆ
function redistributeImages(markdown: string): string {
  const lines = markdown.split('\n');
  const totalLines = lines.length;

  // หาตำแหน่งของรูปภาพทั้งหมด (รูป markdown ที่ไม่ใช่ placeholder)
  const imageIndices: number[] = [];
  lines.forEach((line, idx) => {
    if (line.trim().match(/^!\[.*\]\(.*\)/) && !line.includes('[GEMINI_IMAGE_PROMPT')) {
      imageIndices.push(idx);
    }
  });

  // ถ้ามีรูปน้อยกว่า 2 รูป หรือไม่มี H2 ก็ไม่ต้องกระจาย
  if (imageIndices.length < 2) return markdown;

  // ตรวจสอบว่ารูปกองกันอยู่ท้ายบทความหรือไม่
  // คำนวณตำแหน่งเฉลี่ยของรูป (0-1) — ถ้า > 0.6 แปลว่ากองท้าย
  const avgPosition = imageIndices.reduce((sum, idx) => sum + idx, 0) / (imageIndices.length * totalLines);
  if (avgPosition < 0.6) {
    return markdown; // รูปกระจายอยู่แล้ว ไม่ต้องแก้
  }

  console.log(`[Image Redistribute] พบรูป ${imageIndices.length} รูป กองอยู่ท้าย (avg pos: ${avgPosition.toFixed(2)}) — กำลังกระจายใหม่`);

  // หาตำแหน่ง H2 ทั้งหมด
  const h2Indices: number[] = [];
  lines.forEach((line, idx) => {
    if (line.trim().startsWith('## ') && !line.trim().startsWith('### ')) {
      h2Indices.push(idx);
    }
  });

  if (h2Indices.length === 0) return markdown;

  // ดึงรูปทั้งหมดออกมา (พร้อมบรรทัดว่างติดไปด้วย)
  const images: string[] = [];
  const linesWithoutImages = lines.filter((line, idx) => {
    if (imageIndices.includes(idx)) {
      images.push(line);
      return false;
    }
    return true;
  });

  // กระจายรูปไปยัง H2 ต่างๆ อย่างสม่ำเสมอ
  // ใส่รูปแรกหลัง H2 แรก, รูปที่สองหลัง H2 ตรงกลาง, ฯลฯ
  const h2Positions: number[] = [];
  linesWithoutImages.forEach((line, idx) => {
    if (line.trim().startsWith('## ') && !line.trim().startsWith('### ')) {
      h2Positions.push(idx);
    }
  });

  if (h2Positions.length === 0 || images.length === 0) {
    // fallback: คืน markdown เดิมถ้าไม่มี H2 หลังลบรูป
    return markdown;
  }

  // คำนวณตำแหน่งที่จะแทรกรูป (กระจายตาม H2)
  const insertPositions: number[] = [];
  for (let i = 0; i < images.length; i++) {
    const h2Idx = Math.floor((i * h2Positions.length) / images.length);
    // แทรกหลังเนื้อหา 2-3 บรรทัดของ H2 section
    const insertPos = Math.min(h2Positions[h2Idx] + 3, linesWithoutImages.length);
    insertPositions.push(insertPos);
  }

  // เรียงตำแหน่งจากมากไปน้อย เพื่อให้ splice ไม่กระทบ index อื่น
  const insertions = insertPositions.map((pos, i) => ({ pos, image: images[i] }));
  insertions.sort((a, b) => b.pos - a.pos);

  const result = [...linesWithoutImages];
  for (const { pos, image } of insertions) {
    result.splice(pos, 0, '', image, '');
  }

  return result.join('\n');
}

// Regex ที่ทนทาน — รองรับ marker ที่ AI สร้างผิดรูปแบบหลายแบบ:
//  1. [GEMINI_IMAGE_PROMPT: prompt | 16:9]            ← มาตรฐาน
//  2. [GEMINI_IMAGE_PROMPT: prompt | 16:9)            ← ปิดผิดด้วย )
//  3. [GEMINI_IMAGE_PROMPT: prompt, 16:9] | 16:9)      ← AR ซ้ำ (อยู่ใน prompt + ข้างนอก)
//  4. [GEMINI_IMAGE_PROMPT: prompt, 16:9]             ← AR อยู่ข้างใน prompt อย่างเดียว
const IMAGE_MARKER_REGEX = /\[GEMINI_IMAGE_PROMPT:\s*([\s\S]+?)\s*(?:\|\s*(\d+:\d+)\s*)?[\]\)](?:\s*\|\s*\d+:\d+\s*\)?)?/g;

// Parse marker ที่ AI สร้างมา (อาจผิดรูปแบบ) ให้ได้ prompt สะอาด + AR ที่ถูกต้อง
function parseImageMatch(rawPrompt: string, rawAr: string | undefined, fallbackAr: string): { prompt: string; ar: string } {
  let prompt = rawPrompt.trim();
  // ล้าง AR และ `]` ที่ AI อาจใส่ติดมาใน prompt (เช่น "prompt, 16:9]" → "prompt")
  prompt = prompt.replace(/\s*,?\s*\d+:\d+\s*\]?\s*$/i, '').trim();
  prompt = prompt.replace(/\]+$/, '').trim();

  // หา AR — ลำดับความสำคัญ: จาก `|` > จาก prompt ดั้งเดิม > fallback
  let ar = rawAr;
  if (!ar) {
    const arMatch = rawPrompt.match(/(\d+:\d+)\s*\]?\s*$/);
    ar = arMatch?.[1];
  }
  if (!ar || !["1:1", "16:9", "4:3", "3:4", "9:16"].includes(ar)) {
    ar = ["1:1", "16:9", "4:3", "3:4", "9:16"].includes(fallbackAr) ? fallbackAr : "1:1";
  }
  return { prompt, ar };
}

export async function generateArticle(
  keyword: string,
  title: string | undefined,
  config: {
    language: string;
    tone: string;
    pov: string;
    lengthWords: number;
    audience: string;
    secondaryKeywords: string[];
    copywritingFramework?: string;
    coverToggle: boolean;
    inlineCount: number;
    aspectRatio: string;
    outline?: string[];
    sitemaps?: string[];
    includeLinks?: string[];
    includeSources?: string[];
    excludeSources?: string[];
    targetCountry?: string;
    formality?: string;
    formattingBold?: boolean;
    formattingItalics?: boolean;
    formattingTables?: boolean;
    formattingQuotes?: boolean;
    formattingLists?: boolean;
    headingCase?: string;
    knowledgeMode?: string;
    cta?: string;
    keyTakeaways?: boolean;
    conclusion?: boolean;
    faqs?: boolean;
    articleSize?: string;
    linksPerH2?: number;
    autoExternalLinks?: boolean;
    autoYoutube?: boolean;
    customApiKey?: string;
    customOpenAiApiKey?: string;
    textApiModel?: string;
    textApiBaseUrl?: string;
    textApiPrompt?: string;
    imageApiModel?: string;
    imageApiBaseUrl?: string;
    imageApiPrompt?: string;
  },
  onChunk?: (partialText: string, stage: 'text' | 'image' | 'done') => void
): Promise<string> {
  const isThai = config.language === 'thai';
  const width = config.aspectRatio === '1:1' ? 800 : 1280;
  const height = config.aspectRatio === '1:1' ? 800 : 720;

  const [resolvedTextApiPrompt, resolvedImageApiPrompt] = await Promise.all([
    resolvePromptUrls(config.textApiPrompt || ''),
    resolvePromptUrls(config.imageApiPrompt || '')
  ]);

  const systemPrompt = `You are an expert SEO article writer. Your task is to write a highly optimized, engaging, and informative article.
Language: ${isThai ? 'Thai' : 'English'}
Target Country: ${config.targetCountry === 'thailand' ? 'Thailand' : 'United States (Default)'}
Tone: ${config.tone}
Formality: ${config.formality || 'Automatic'}
Point of View: ${config.pov === 'first' ? 'First Person (I/We)' : config.pov === 'second' ? 'Second Person (You)' : 'Third Person (He/She/It/They)'}
Target Length: Approximately ${config.lengthWords} words — you MUST write at least ${Math.round(config.lengthWords * 0.85)} words. Do NOT stop early. Expand each section thoroughly.
Target Audience: ${config.audience || 'General public'}
${config.copywritingFramework === 'auto' ? `Copywriting Framework: Analyze the "Title" and "Keywords" to determine the best structure for this topic. You MUST choose and apply ONE of these three frameworks:
1. PAS (Problem-Agitate-Solve) - Use if the topic is about solving a specific pain point or problem.
2. AIDA (Attention-Interest-Desire-Action) - Use if the topic is persuasive, product-driven, or conversion-focused.
3. Standard SEO Structure (Introduction, Main Headings, Subheadings, Conclusion) - Use for general informational, educational, or standard guide content.
Apply the chosen framework organically to the article structure.` : config.copywritingFramework ? `Copywriting Framework: Use the ${config.copywritingFramework} framework to structure the content.` : 'Content Structure: Use a standard SEO-optimized informational structure (Introduction, Main Headings, Subheadings, Conclusion).'}

${resolvedTextApiPrompt ? `CUSTOM USER INSTRUCTIONS FOR TEXT GENERATION (IMPORTANT):
${resolvedTextApiPrompt}\n` : ''}

KEYWORD INTEGRATION:
- You MUST naturally weave the "Primary Keyword" and all "Secondary Keywords" into the content.
- Ensure the Primary Keyword appears in the first 100 words and last 100 words.
- Distribute Secondary Keywords throughout the article in relevant sections.

FORMATTING RULES:
- CRITICAL WRITING GUIDELINES: Do NOT hallucinate facts or write nonsensical content. The article must be highly logical, factually correct, and use appropriate, professional terminology. Avoid rambling, repeating points needlessly, or writing "mushy" content.
- NEVER translate English idioms or technical terms literally. Use natural, professional Thai industry jargon. Do NOT invent new words or use archaic terms.
${isThai ? `- CRITICAL THAI SPELLING RULE: You MUST write every Thai word COMPLETELY. Never drop or omit the final character of any Thai word. For example, ALWAYS write "การออกแบบ" (never "การออกแบ"), "หรืออาคาร" (never "หรือาคาร"), "เกมมือถือ" (never "เกมือถือ"), "โรงงาน" (never "โรงาน"). Double-check every word before outputting.
- Always insert a space after words ending in "การ", "การณ์", "ภัย", "บันได" and before the next word or sentence to avoid words merging together.` : ''}

${isThai ? `- For Thai articles, use these Thai labels for standard sections: 
    "Key Takeaways" -> "สรุปประเด็นสำคัญ"
    "Conclusion" -> "บทสรุป"
    "Frequently Asked Questions" -> "คำถามที่พบบ่อย"
    "Table of Contents" -> "สารบัญ"` : ''}
${config.formattingBold !== false ? '- Use **bold** for important keywords and emphasis.' : '- Do not bold text.'}
${config.formattingItalics !== false ? '- Use *italics* for minor emphasis.' : '- Do not italicize text.'}
${config.formattingTables !== false ? '- Include Markdown tables where data could be organized.' : '- Do not use tables.'}
${config.formattingQuotes !== false ? '- Use > blockquotes for tips, quotes, or important notes.' : '- Do not use blockquotes.'}
${config.formattingLists !== false ? '- Use lists (bulleted or numbered) where appropriate.' : '- Avoid using lists.'}
- Headings Case: ${config.headingCase === 'lower' ? 'use lower case for all headings' : config.headingCase === 'sentence' ? 'Use Sentence case for all headings' : 'Use Title Case for all Headings'}

STRUCTURE RULES:
${config.outline && config.outline.length > 0 ? `OUTLINE STRUCTURE (MUST FOLLOW EXACTLY):
- ${config.outline.join('\n- ')}\n` : ''}
${config.keyTakeaways !== false ? `- Include a "${isThai ? 'สรุปประเด็นสำคัญ' : 'Key Takeaways'}" bulleted list at the beginning (after the H1 and intro).` : ''}
${config.cta ? `- Add a Call-to-Action (CTA) section with an H3 pointing to this URL: ${config.cta}` : ''}
${config.conclusion !== false ? `- Always end with a "${isThai ? 'บทสรุป' : 'Conclusion'}" section as the last H2.` : ''}
${config.faqs !== false ? `- Add a "${isThai ? 'คำถามที่พบบ่อย' : 'Frequently Asked Questions'}" (FAQs) section after the conclusion.` : ''}

${config.includeSources && config.includeSources.length > 0 ? `REFERENCE / KNOWLEDGE TO INCLUDE:
- ${config.includeSources.join('\n- ')}\n` : ''}
${config.excludeSources && config.excludeSources.length > 0 ? `DO NOT MENTION OR USE THESE SOURCES:
- ${config.excludeSources.join('\n- ')}\n` : ''}
${config.includeLinks && config.includeLinks.length > 0 || config.sitemaps && config.sitemaps.length > 0 ? `INTERNAL / EXTERNAL LINKS TO DISTRIBUTE:
${config.sitemaps && config.sitemaps.length > 0 ? `Sitemaps:\n- ${config.sitemaps.join('\n- ')}\n` : ''}${config.includeLinks && config.includeLinks.length > 0 ? `Links to insert naturally:\n- ${config.includeLinks.join('\n- ')}\n` : ''}
Distribute roughly ${config.linksPerH2 ?? 2} links per H2 section.` : ''}

IMAGE INSTRUCTIONS:
CRITICAL IMAGE MARKER RULES (read carefully to avoid errors):
- You MUST NOT use real image URLs. You MUST use the exact placeholder format below.
- The image placeholder format MUST be exactly: ![Alt Text]([GEMINI_IMAGE_PROMPT: <english prompt here> | <aspect-ratio>])
- The aspect-ratio appears ONLY ONCE, AFTER the pipe character, then closing bracket ]
- NEVER write the aspect-ratio inside the prompt text itself
- The marker MUST end with ], NEVER with )
- Correct example: ![Warehouse Forklift]([GEMINI_IMAGE_PROMPT: realistic photo of a forklift in a modern warehouse with shelves | 16:9])
- WRONG (do not do this): ![Alt]([GEMINI_IMAGE_PROMPT: forklift photo, 16:9] | 16:9)
${config.coverToggle ? `- MUST include 1 COVER IMAGE at the very beginning of the article. Copy this template and replace only the <english prompt here> part: ![Cover Image]([GEMINI_IMAGE_PROMPT: <english prompt here> | ${config.aspectRatio}])` : '- Do NOT include a cover image.'}
${config.inlineCount > 0 ? `- MUST insert EXACTLY ${config.inlineCount} INLINE IMAGES distributed EVENLY across the article body.
- TOTAL IMAGES REQUIRED: ${(config.coverToggle ? 1 : 0) + config.inlineCount} images (${config.coverToggle ? '1 Cover Image + ' : ''}${config.inlineCount} Inline Images). Do NOT generate fewer images than requested!
- Place one image under each H2 heading spread throughout the article.
- Use this template for each image (replace only the <english prompt here> part, keep the same aspect-ratio ${config.aspectRatio || '16:9'}): ![Related Alt Text]([GEMINI_IMAGE_PROMPT: <english prompt here> | ${config.aspectRatio || '16:9'}])
- CRITICAL STRICT RULE: The image prompt (<english prompt here>) MUST BE 100% IN ENGLISH. Do NOT use Thai. Seeddream only understands English. If you use Thai, the image will be completely wrong.
- The image prompt must be highly descriptive and relevant to the section content. Do NOT include any text, words, or letters in the generated image.
- CRITICAL: Images MUST be distributed across the article body, NOT grouped together at the end.` : '- Do NOT include inline images.'}
`;

  const userPrompt = `Please write an SEO optimized article.
Primary Keyword: ${keyword}
${title ? `Suggested Title: ${title}` : ''}
${config.secondaryKeywords.length > 0 ? `Secondary Keywords to include: ${config.secondaryKeywords.join(', ')}` : ''}

IMPORTANT: Write at least ${Math.round(config.lengthWords * 0.85)} words. Expand each H2 section thoroughly with detailed explanations, examples, and insights. Do NOT stop early.
Output the article in Markdown format. Use proper heading tags (H1, H2, H3), bullet points where appropriate, and ensure the content flows naturally, provides real value, and is highly optimized. Don't forget to inject the markdown images using the exact custom syntax requested.`;

  try {
    // We are deliberately moving to client-side fetching as requested to support static Netlify deployments.
    // Ensure you configure 'VITE_GEMINI_API_KEY' in your Netlify Environment Variables.
    // บังคับใช้ global API Key ของระบบ (admin ตั้งค่าในหน้า Admin) เสมอ
    // ผู้ใช้ทั่วไปไม่สามารถใช้ API Key ของตัวเองได้อีกต่อไป
    const apiKey: string = "__USE_GLOBAL__";

    // Mask key for debugging
    const maskedKey = '[GLOBAL-ADMIN-KEY]';
    console.log(`[AI API Log] Using API Key: ${maskedKey}`);

    const prompt = `System Instructions: ${systemPrompt}\n\nUser Request: ${userPrompt}`;

    let finalMarkdown = "";
    // เก็บ promise สำหรับรูปภาพที่เริ่ม generate แล้วระหว่าง streaming
    const earlyImagePromises: Map<number, Promise<string>> = new Map();
    const earlyImageMatches: Array<{ prompt: string, ar: string }> = [];
    const imageRegexLive = new RegExp(IMAGE_MARKER_REGEX.source, 'g');
    const detectedImageKeys = new Set<string>(); // track รูปที่ตรวจจับแล้ว ป้องกัน scan ซ้ำ

    try {
      // บังคับ: ส่ง marker '__GLOBAL_TEXT__' ให้ server ดึง model/baseUrl จาก DB เสมอ
      // (ไม่สนค่า textApiModel/baseUrl ที่ค้างอยู่ใน localStorage ของ client)
      const requestModel: string = '__GLOBAL_TEXT__';

      // ลอง streaming ก่อน (เร็วกว่า + เห็นข้อความทันที) ถ้าล้มเหลวจะ fallback ไป non-streaming
      try {
        const textAbort = new AbortController();
        const textTimeout = setTimeout(() => textAbort.abort(), 600000); // 10 นาที (เพิ่มจาก 5 นาที)
        const streamResponse = await fetch('/api/gemini/stream-text', {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "x-api-key": apiKey
          },
          body: JSON.stringify({
            model: requestModel,
            contents: prompt,
            // ไม่ส่ง baseUrl เมื่อใช้ global — ให้ server ดึงจาก DB ทั้งหมด
            config: apiKey === '__USE_GLOBAL__' ? {} : { baseUrl: config.textApiBaseUrl }
          }),
          signal: textAbort.signal
        });
        clearTimeout(textTimeout);

        if (streamResponse.ok && streamResponse.body) {
          const reader = streamResponse.body.getReader();
          const decoder = new TextDecoder();
          let buffer = '';

          while (true) {
            const { done, value } = await reader.read();
            if (done) break;
            buffer += decoder.decode(value, { stream: true });
            const lines = buffer.split('\n');
            buffer = lines.pop() || '';

            for (const line of lines) {
              const trimmed = line.trim();
              if (trimmed.startsWith('data: ')) {
                const data = trimmed.slice(6);
                if (data === '[DONE]') continue;
                try {
                  const parsed = JSON.parse(data);
                  if (parsed.error) {
                    throw new Error(typeof parsed.error === 'string' ? parsed.error : JSON.stringify(parsed.error));
                  }
                  // ตรวจสอบ finish_reason — ถ้าเป็น "length" แปลว่าถูกตัดเพราะ token limit
                  const finishReason = parsed.choices?.[0]?.finish_reason;
                  if (finishReason === 'length') {
                    console.warn('[AI] Stream ถูกตัดเพราะ max_tokens ไม่พอ — บทความอาจไม่สมบูรณ์');
                  }
                  const content = parsed.choices?.[0]?.delta?.content || '';
                  if (content) {
                    finalMarkdown += content;
                    // ตรวจจับ image placeholder ทันทีระหว่าง stream (แค่รูปใหม่เท่านั้น)
                    imageRegexLive.lastIndex = 0;
                    let liveMatch;
                    while ((liveMatch = imageRegexLive.exec(finalMarkdown)) !== null) {
                      const parsed = parseImageMatch(liveMatch[1], liveMatch[2], config.aspectRatio || '1:1');
                      const imageKey = parsed.prompt + '|' + parsed.ar;
                      if (detectedImageKeys.has(imageKey)) continue; // skip รูปที่เคย detect แล้ว
                      detectedImageKeys.add(imageKey);
                      const imgIdx = earlyImageMatches.length;
                      const imgPrompt = parsed.prompt;
                      const ar = parsed.ar;
                      earlyImageMatches.push({ prompt: imgPrompt, ar });
                      // เริ่มสร้างรูปภาพทันที (parallel กับ text stream)
                      earlyImagePromises.set(imgIdx, scheduleImage(() => generateSingleImage(imgIdx, imgPrompt, ar, config, resolvedImageApiPrompt)));
                    }
                    onChunk?.(finalMarkdown, 'text');
                  }
                } catch (e: any) {
                  if (e.message && !e.message.includes('JSON')) throw e;
                }
              }
            }
          }
        } else {
          // Fallback: streaming ล้มเหลว ใช้ non-streaming
          throw new Error('Streaming unavailable, falling back');
        }
      } catch (streamErr: any) {
        if (streamErr.message !== 'Streaming unavailable, falling back') {
          console.warn('[AI] Streaming failed, falling back to non-streaming:', streamErr.message);
        }
        const fallbackAbort = new AbortController();
        const fallbackTimeout = setTimeout(() => fallbackAbort.abort(), 300000); // 5 นาที
        const response = await fetch('/api/gemini/generate', {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "x-api-key": apiKey
          },
          body: JSON.stringify({
            model: requestModel,
            contents: prompt,
            config: apiKey === '__USE_GLOBAL__' ? {} : { baseUrl: config.textApiBaseUrl }
          }),
          signal: fallbackAbort.signal
        });
        clearTimeout(fallbackTimeout);

        if (!response.ok) {
          const errorData = await response.json().catch(() => null);
          let errorMessage = errorData?.error || "Failed to generate content";
          if (typeof errorMessage === 'string') {
            try {
              const parsed = JSON.parse(errorMessage);
              if (parsed.error && parsed.error.message) {
                errorMessage = parsed.error.message;
              }
            } catch (e) { }
          }
          throw new Error(typeof errorMessage === 'string' ? errorMessage : JSON.stringify(errorMessage));
        }

        const data = await response.json();
        finalMarkdown = data.text || data.candidates?.[0]?.content?.parts?.[0]?.text || "";
        onChunk?.(finalMarkdown, 'text');
      }

      // Some AI models (like Z.ai) wrap the entire response in a markdown code block
      finalMarkdown = finalMarkdown.replace(/^```(?:markdown|md)?\s*\n/i, '');
      finalMarkdown = finalMarkdown.replace(/\n```\s*$/i, '');
      finalMarkdown = finalMarkdown.trim();

      // Post-processing: แก้คำผิดไทยหลัง AI สร้างเสร็จ (ไม่กินเวลา generate)
      if (isThai) {
        finalMarkdown = fixThaiTypos(finalMarkdown);
      }

      // NOTE: AI Proofreading ถูกปิดไว้ชั่วคราว
      // เหตุผล: การใช้ model เดียวกันสำหรับ generate + proofread ไม่ได้ผล
      // เพราะ AI ที่ generate คำผิดออกมา จะมองว่าคำผิดนั้น "ถูกต้อง" อีกครั้งตอน proofread
      // หากจะเปิดใช้ ต้องใช้ model อื่นสำหรับ proofreading (เช่น GPT-4o-mini)
      // onChunk?.(finalMarkdown, 'text');
      // finalMarkdown = await proofreadWithAI(finalMarkdown, config, '__USE_GLOBAL__', '__GLOBAL_TEXT__');
      // onChunk?.(finalMarkdown, 'text');
    } catch (restError: any) {
      console.warn("REST API text generation failed:", restError);
      throw restError;
    }

    // Post-processing: แทนที่ image placeholders ด้วยรูปภาพที่สร้างแล้ว
    onChunk?.(finalMarkdown, 'image');
    
    // Check if AI missed generating images and append missing ones
    const expectedImages = config.inlineCount + (config.coverToggle ? 1 : 0);
    const existingMatches = [...finalMarkdown.matchAll(new RegExp(IMAGE_MARKER_REGEX.source, 'g'))];
    if (existingMatches.length < expectedImages) {
      console.warn(`[Image Check] AI generated only ${existingMatches.length} images out of ${expectedImages}. Appending missing placeholders.`);
      for (let i = existingMatches.length; i < expectedImages; i++) {
        finalMarkdown += `\n\n![Image ${i+1}]([GEMINI_IMAGE_PROMPT: ${resolvedImageApiPrompt || `detailed realistic photo about ${keyword}`} | ${config.aspectRatio || '16:9'}])\n\n`;
      }
    }

    const imageRegex = new RegExp(IMAGE_MARKER_REGEX.source, 'g');
    const matches = [...finalMarkdown.matchAll(imageRegex)];

    if (matches.length > 0) {
      const imageGenApiKey = (config.customOpenAiApiKey && config.customOpenAiApiKey.trim()) || "YOUR_OPENAI_API_KEY";

      if (!imageGenApiKey || imageGenApiKey.trim() === "YOUR_OPENAI_API_KEY") {
        console.warn("No valid API Key provided for image generation, skipping image generation.");
        for (let i = 0; i < matches.length; i++) {
          finalMarkdown = finalMarkdown.replace(matches[i][0], `> *(รูปภาพถูกข้าม: ไม่มี API Key สำหรับสร้างรูปภาพ)*\n\n`);
        }
        return finalMarkdown;
      }

      const replacements: string[] = new Array(matches.length);
      const imagePromises = matches.map(async (match, i) => {
        // ถ้าเคณสร้างรูปภาพนี้ไปแล้วระหว่าง streaming ใช้ผลเดิม
        if (earlyImagePromises.has(i)) {
          try {
            replacements[i] = await earlyImagePromises.get(i)!;
            return;
          } catch (e) {
            // ถ้ารูปที่สร้างไปล้มเหลว สร้างใหม่
          }
        }

        const parsed = parseImageMatch(match[1], match[2], config.aspectRatio || '1:1');
        const imagePrompt = parsed.prompt;
        const ar = parsed.ar;

        try {
          replacements[i] = await scheduleImage(() => generateSingleImage(i, imagePrompt, ar, config, resolvedImageApiPrompt));
        } catch (err: any) {
          const errorMsg = err?.message || JSON.stringify(err);
          if (errorMsg.includes('429') || errorMsg.includes('quota')) {
            replacements[i] = `> *(รูปภาพถูกข้าม: โควต้าระบบสร้างภาพเต็ม)*`;
          } else {
            replacements[i] = `> *(รูปภาพถูกข้าม: ${errorMsg})*`;
          }
        }
      });

      await Promise.all(imagePromises);

      let i = 0;
      finalMarkdown = finalMarkdown.replace(imageRegex, () => replacements[i++]);

      // Post-processing: ถ้ารูปทั้งหมดถูกกองไว้ท้ายบทความ → กระจายใหม่ให้สมดุล
      finalMarkdown = redistributeImages(finalMarkdown);
    }

    return finalMarkdown;
  } catch (error: any) {
    console.error("Generate content error:", error);
    const errorMsg = error.message || 'Unknown error';
    if (errorMsg === "Failed to fetch" || errorMsg.includes("Failed to fetch")) {
      throw new Error("เกิดข้อผิดพลาดในการเชื่อมต่อกับเซิร์ฟเวอร์ (Failed to fetch) - กรุณาลองกดสร้างใหม่อีกครั้ง");
    }
    if (errorMsg.includes('429') || errorMsg.includes('RESOURCE_EXHAUSTED') || errorMsg.includes('quota') || errorMsg.includes('exceeded')) {
      throw new Error(`โควต้า API เต็ม (Rate Limit 429) กรุณาไปที่หน้าตั้งค่าและตรวจสอบ API Key ของคุณ หรือรอสักครู่แล้วลองใหม่`);
    }
    throw new Error(errorMsg);
  }
}


